extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  - vocab.txt
  - extensions.txt
filters:
  # Exclude checking list of contributor names on release notes:
  - '(?s)<h3 id=.*>Contributors</h3>.*'
